#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "parser.h"

int main(int argc, char ** argv){
	int choice;
	printf("Press option for the defined task.\n");
	printf("1 : For removal of comments ‐ print the comment free code on the console.\n");
	printf("2 : For printing the token list (on the console) generated by the lexer.\n");
	printf("3 : For parsing to verify the syntactic correctness of the input source code.\n");
	printf("4 : For printing the parse tree appropriately.\n");
	printf("Enter your choice: ");
	scanf("%d", &choice);
	FILE *fp = NULL;
	tokenInfo *ti = NULL;

	nonTerminalList * ntlHead = NULL;
	parseTree * ptHead = NULL;
// 	// printGrammar(ntl);
// 	computeFirstSet(ntl);
// 	// printFirstSet(ntl);
// 	// computeFollowSet(ntl);
// 	readFollowSet("follow.txt",ntl);
// 	// printFollowSet(ntl);
// 	generateParseTable(ntl);
// 	// printParseTable();
// 	generateParseTree(charv[1]);
// 	printParseTree(ptHead);

	switch(choice){
		case 1:
				printf("%s\n", argv[1]);
				removeComments(argv[1]);
				break;
		case 2:
				fp = fopen(argv[1], "r");
				ti = getNextToken(fp);
				while( strcmp(ti->token,"EOF")  != 0){
					readTokenInfo(ti);
					ti = getNextToken(fp);
				}
				fclose(fp);
				break;
		case 3:	
				ntlHead = readGrammar("grammar.txt");
				computeFirstSet(ntlHead);
				readFollowSet("follow.txt",ntlHead);
				generateParseTable(ntlHead);
				ptHead = initParseTree(ptHead);
				generateParseTree(ptHead, argv[1]);
				break;
		case 4:	
				ntlHead = readGrammar("grammar.txt");
				computeFirstSet(ntlHead);
				readFollowSet("follow.txt",ntlHead);
				generateParseTable(ntlHead);
				ptHead = initParseTree(ptHead);
				generateParseTree(ptHead, argv[1]);
				// printf("%s\n", ptHead->parent->value);
				// printf("%s\n", ptHead->value);
				// printf("%s\n", ptHead->child->value);
				// printf("%s\n", ptHead->child->sibling->value);
				// printf("%s\n", ptHead->child->sibling->sibling->value);
				// printf("%s\n", ptHead->child->sibling->sibling->sibling->value);
				printParseTree(ptHead);
				break;
		default:
				printf("Invalid Choice!\n");
	}
	return 0;
}